// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.6
// source: import.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvailableSystemObjects int32

const (
	AvailableSystemObjects_cc_queue          AvailableSystemObjects = 0
	AvailableSystemObjects_schema            AvailableSystemObjects = 1
	AvailableSystemObjects_users             AvailableSystemObjects = 2
	AvailableSystemObjects_devices           AvailableSystemObjects = 3
	AvailableSystemObjects_calendars         AvailableSystemObjects = 4
	AvailableSystemObjects_cc_list           AvailableSystemObjects = 5
	AvailableSystemObjects_cc_team           AvailableSystemObjects = 6
	AvailableSystemObjects_cc_agent          AvailableSystemObjects = 7
	AvailableSystemObjects_cc_resource       AvailableSystemObjects = 8
	AvailableSystemObjects_cc_resource_group AvailableSystemObjects = 9
	AvailableSystemObjects_chat_bots         AvailableSystemObjects = 10
	AvailableSystemObjects_skills            AvailableSystemObjects = 11
	AvailableSystemObjects_buckets           AvailableSystemObjects = 12
)

// Enum value maps for AvailableSystemObjects.
var (
	AvailableSystemObjects_name = map[int32]string{
		0:  "cc_queue",
		1:  "schema",
		2:  "users",
		3:  "devices",
		4:  "calendars",
		5:  "cc_list",
		6:  "cc_team",
		7:  "cc_agent",
		8:  "cc_resource",
		9:  "cc_resource_group",
		10: "chat_bots",
		11: "skills",
		12: "buckets",
	}
	AvailableSystemObjects_value = map[string]int32{
		"cc_queue":          0,
		"schema":            1,
		"users":             2,
		"devices":           3,
		"calendars":         4,
		"cc_list":           5,
		"cc_team":           6,
		"cc_agent":          7,
		"cc_resource":       8,
		"cc_resource_group": 9,
		"chat_bots":         10,
		"skills":            11,
		"buckets":           12,
	}
)

func (x AvailableSystemObjects) Enum() *AvailableSystemObjects {
	p := new(AvailableSystemObjects)
	*p = x
	return p
}

func (x AvailableSystemObjects) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvailableSystemObjects) Descriptor() protoreflect.EnumDescriptor {
	return file_import_proto_enumTypes[0].Descriptor()
}

func (AvailableSystemObjects) Type() protoreflect.EnumType {
	return &file_import_proto_enumTypes[0]
}

func (x AvailableSystemObjects) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvailableSystemObjects.Descriptor instead.
func (AvailableSystemObjects) EnumDescriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{0}
}

type Lookup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Lookup) Reset() {
	*x = Lookup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lookup) ProtoMessage() {}

func (x *Lookup) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lookup.ProtoReflect.Descriptor instead.
func (*Lookup) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{0}
}

func (x *Lookup) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lookup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_import_proto protoreflect.FileDescriptor

var file_import_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x06, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x2a, 0xd1, 0x01, 0x0a, 0x16, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12,
	0x0c, 0x0a, 0x08, 0x63, 0x63, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x10,
	0x03, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x73, 0x10, 0x04,
	0x12, 0x0b, 0x0a, 0x07, 0x63, 0x63, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x10, 0x05, 0x12, 0x0b, 0x0a,
	0x07, 0x63, 0x63, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x63, 0x63,
	0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x63, 0x63, 0x5f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x10, 0x08, 0x12, 0x15, 0x0a, 0x11, 0x63, 0x63, 0x5f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x10, 0x09,
	0x12, 0x0d, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x62, 0x6f, 0x74, 0x73, 0x10, 0x0a, 0x12,
	0x0a, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x10, 0x0b, 0x12, 0x0b, 0x0a, 0x07, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x10, 0x0c, 0x42, 0x16, 0x5a, 0x14, 0x77, 0x65, 0x62, 0x69,
	0x74, 0x65, 0x6c, 0x5f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_import_proto_rawDescOnce sync.Once
	file_import_proto_rawDescData = file_import_proto_rawDesc
)

func file_import_proto_rawDescGZIP() []byte {
	file_import_proto_rawDescOnce.Do(func() {
		file_import_proto_rawDescData = protoimpl.X.CompressGZIP(file_import_proto_rawDescData)
	})
	return file_import_proto_rawDescData
}

var file_import_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_import_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_import_proto_goTypes = []interface{}{
	(AvailableSystemObjects)(0), // 0: logger.AvailableSystemObjects
	(*Lookup)(nil),              // 1: logger.Lookup
}
var file_import_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_import_proto_init() }
func file_import_proto_init() {
	if File_import_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_import_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lookup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_import_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_import_proto_goTypes,
		DependencyIndexes: file_import_proto_depIdxs,
		EnumInfos:         file_import_proto_enumTypes,
		MessageInfos:      file_import_proto_msgTypes,
	}.Build()
	File_import_proto = out.File
	file_import_proto_rawDesc = nil
	file_import_proto_goTypes = nil
	file_import_proto_depIdxs = nil
}
