package viber

import "strings"

var viberEmojiMap = map[string]string{
	"(smiley)":    "😀",
	"(sad)":       "😢",
	"(wink)":      "😉",
	"(angry)":     "😡",
	"(inlove)":    "😍",
	"(yummi)":     "😋",
	"(laugh)":     "😃",
	"(surprised)": "😲",
	"(moa)":       "😘",
	"(happy)":     "😊",
	"(cry)":       "😭",
	"(sick)":      "😷",
	"(shy)":       "😳",
	"(teeth)":     "😁",
	"(tongue)":    "😛",
	"(money)":     "🤑",
	"(mad)":       "😠",
	"(flirt)":     "😘",
	"(crazy)":     "🤪",
	"(confused)":  "😕",
	"(depressed)": "😔",
	"(scream)":    "😱",
	"(nerd)":      "🤓",
	"(not_sure)":  "😕",
	"(cool)":      "😎",
	"(huh)":       "😧",
	"(happycry)":  "😂",
	"(mwah)":      "😘",
	"(exhausted)": "😩",
	"(eek)":       "😬",
	"(dizzy)":     "😵",
	"(dead)":      "😵",
	"(straight)":  "😐",
	"(yo)":        "😏",
	"(wtf)":       "😡",
	"(ohno)":      "😧",
	"(oh)":        "😯",
	"(wink2)":     "😉",
	"(what)":      "🤨",
	"(weak)":      "😫",
	"(upset)":     "😠",
	"(ugh)":       "😣",
	"(singing)":   "😙",
	"(silly)":     "😜",
	"(meh)":       "😐",

	"(devil)": "😈",
	"(angel)": "😇",

	"(heart)":        "❤️",
	"(heart_break)":  "💔",
	"(purple_heart)": "💜",
	"(unlike)":       "👎",
	"(like)":         "👍",
	"(V)":            "✌️",
	"(fu)":           "🖕",
	"(clap)":         "👏",
	"(rockon)":       "🤘",
	"(angrymark)":    "💢",
	"(thinking)":     "💬",
	"(zzz)":          "💤",
	"(!)":            "❗",
	"(Q)":            "❓",

	"(diamond)":    "💎",
	"(trophy)":     "🏆",
	"(crown)":      "👑",
	"(ring)":       "💍",
	"($)":          "💵",
	"(hammer)":     "🔨",
	"(wrench)":     "🔧",
	"(key)":        "🔑",
	"(lock)":       "🔒",
	"(video)":      "📹",
	"(TV)":         "📺",
	"(trumpet)":    "🎺",
	"(guitar)":     "🎸",
	"(speaker)":    "🔊",
	"(music)":      "🎵",
	"(microphone)": "🎤",
	"(bell)":       "🔔",

	"(koala)":    "🐨",
	"(sheep)":    "🐑",
	"(ladybug)":  "🐞",
	"(chick)":    "🐣",
	"(monkey)":   "🐵",
	"(panda)":    "🐼",
	"(turtle)":   "🐢",
	"(bunny)":    "🐰",
	"(bee)":      "🐝",
	"(bat)":      "🦇",
	"(cat)":      "🐈",
	"(dog)":      "🐕",
	"(snake)":    "🐍",
	"(snail)":    "🐌",
	"(goldfish)": "🐠",
	"(shark)":    "🦈",
	"(pig)":      "🐖",
	"(owl)":      "🦉",
	"(penguin)":  "🐧",
	"(paw)":      "🐾",
	"(poo)":      "💩",

	"(cap)":            "🧢",
	"(partyhat)":       "🎉",
	"(cactus)":         "🌵",
	"(clover)":         "🍀",
	"(sprout)":         "🌱",
	"(palmtree)":       "🌴",
	"(christmas_tree)": "🎄",
	"(mapleleaf)":      "🍁",
	"(flower)":         "🌼",
	"(sunflower)":      "🌻",
	"(sun)":            "🌞",
	"(moon)":           "🌙",
	"(rain)":           "🌧️",
	"(cloud)":          "☁️",
	"(umbrella)":       "☂️",
	"(snowman)":        "⛄",
	"(snowflake)":      "❄️",

	"(telephone)":  "☎️",
	"(phone)":      "📱",
	"(battery)":    "🔋",
	"(time)":       "⏰",
	"(knife)":      "🔪",
	"(syringe)":    "💉",
	"(termometer)": "🌡️",
	"(ruler)":      "📏",
	"(scissor)":    "✂️",
	"(paperclip)":  "📎",
	"(pencil)":     "✏️",
	"(magnify)":    "🔍",
	"(glasses)":    "👓",
	"(book)":       "📘",
	"(letter)":     "✉️",

	"(muscle)":     "💪",
	"(boxing)":     "🥊",
	"(light_bulb)": "💡",
	"(fire)":       "🔥",
	"(bomb)":       "💣",
	"(cigarette)":  "🚬",
	"(kiss)":       "💋",
	"(gift)":       "🎁",
	"(skull)":      "💀",
	"(ghost)":      "👻",

	"(golf)":       "⛳",
	"(football)":   "🏈",
	"(tennis)":     "🎾",
	"(soccer)":     "⚽",
	"(basketball)": "🏀",
	"(baseball)":   "⚾",
	"(8ball)":      "🎱",
	"(balloon1)":   "🎈",
	"(balloon2)":   "🎈",
	"(dice)":       "🎲",
	"(console)":    "🎮",

	"(chicken)":    "🍗",
	"(burger)":     "🍔",
	"(pizza)":      "🍕",
	"(noodles)":    "🍜",
	"(sushi1)":     "🍣",
	"(sushi2)":     "🍣",
	"(donut)":      "🍩",
	"(egg)":        "🥚",
	"(hotdog)":     "🌭",
	"(ice_cream)":  "🍦",
	"(croissant)":  "🥐",
	"(chocolate)":  "🍫",
	"(lollipop)":   "🍭",
	"(popcorn)":    "🍿",
	"(cake)":       "🎂",
	"(cherry)":     "🍒",
	"(banana)":     "🍌",
	"(watermelon)": "🍉",
	"(strawberry)": "🍓",
	"(grapes)":     "🍇",
	"(pineapple)":  "🍍",
	"(corn)":       "🌽",
	"(mushroom)":   "🍄",

	"(beer)":    "🍺",
	"(wine)":    "🍷",
	"(martini)": "🍸",
	"(coffee)":  "☕",

	"(car)":       "🚘",
	"(taxi)":      "🚕",
	"(ambulance)": "🚑",
	"(policecar)": "🚓",
	"(bicycle)":   "🚲",
	"(airplane)":  "✈️",
	"(ufo)":       "🛸",
	"(rocket)":    "🚀",
	"(run)":       "🏃",
}

func parseTextWithEmoji(text string) string {

	for k, v := range viberEmojiMap {
		text = strings.ReplaceAll(text, k, v)
	}

	return text
}
