// this is a partial derived proto interface to verify token authorization
// keep sync with source https://git.webitel.com/projects/CORE/repos/webitel.go/browse/api/proto/authz.proto?at=refs%2Fheads%2Fdev

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: authN.proto

package auth

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserinfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // string id_token = 2;
}

func (x *UserinfoRequest) Reset() {
	*x = UserinfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authN_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserinfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserinfoRequest) ProtoMessage() {}

func (x *UserinfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authN_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserinfoRequest.ProtoReflect.Descriptor instead.
func (*UserinfoRequest) Descriptor() ([]byte, []int) {
	return file_authN_proto_rawDescGZIP(), []int{0}
}

func (x *UserinfoRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// AccessScope represents authorized access level
// to object class declaration within domain namespace
type Objclass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Inherit::ObjectClass
	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`      // class: object id
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`   // class: display common name
	Class string `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"` // class: alphanumeric code name
	// Is [?]-[b]ased [A]ccess [C]ontrol *model enabled ?
	Abac bool `protobuf:"varint,4,opt,name=abac,proto3" json:"abac,omitempty"` // [A]ttribute-[b]ased;  not implemented; next releases ...
	Obac bool `protobuf:"varint,5,opt,name=obac,proto3" json:"obac,omitempty"` // [O]peration-[b]ased;  Mandatory: control access to object.class (alias: collection, section, etc.)
	Rbac bool `protobuf:"varint,6,opt,name=rbac,proto3" json:"rbac,omitempty"` // [R]ecord-[b]ased; Discretionary: control access to object.entry (alias: resource, record, etc.)
	// Extension: discretionary access control
	Access string `protobuf:"bytes,7,opt,name=access,proto3" json:"access,omitempty"` // flags: [ CREATE | SELECT | UPDATE | DELETE ]
}

func (x *Objclass) Reset() {
	*x = Objclass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authN_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Objclass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Objclass) ProtoMessage() {}

func (x *Objclass) ProtoReflect() protoreflect.Message {
	mi := &file_authN_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Objclass.ProtoReflect.Descriptor instead.
func (*Objclass) Descriptor() ([]byte, []int) {
	return file_authN_proto_rawDescGZIP(), []int{1}
}

func (x *Objclass) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Objclass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Objclass) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Objclass) GetAbac() bool {
	if x != nil {
		return x.Abac
	}
	return false
}

func (x *Objclass) GetObac() bool {
	if x != nil {
		return x.Obac
	}
	return false
}

func (x *Objclass) GetRbac() bool {
	if x != nil {
		return x.Rbac
	}
	return false
}

func (x *Objclass) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

//
type ObjectId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // identifier
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // display name
}

func (x *ObjectId) Reset() {
	*x = ObjectId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authN_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectId) ProtoMessage() {}

func (x *ObjectId) ProtoReflect() protoreflect.Message {
	mi := &file_authN_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectId.ProtoReflect.Descriptor instead.
func (*ObjectId) Descriptor() ([]byte, []int) {
	return file_authN_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ObjectId) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// USAGE details
type LicenseUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // license.id
	Prod      string    `protobuf:"bytes,2,opt,name=prod,proto3" json:"prod,omitempty"`                             // license.prod
	User      *ObjectId `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`                             // grant to::user
	IssuedAt  int64     `protobuf:"varint,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`    // not before
	ExpiresAt int64     `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // not after
}

func (x *LicenseUser) Reset() {
	*x = LicenseUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authN_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LicenseUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseUser) ProtoMessage() {}

func (x *LicenseUser) ProtoReflect() protoreflect.Message {
	mi := &file_authN_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseUser.ProtoReflect.Descriptor instead.
func (*LicenseUser) Descriptor() ([]byte, []int) {
	return file_authN_proto_rawDescGZIP(), []int{3}
}

func (x *LicenseUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LicenseUser) GetProd() string {
	if x != nil {
		return x.Prod
	}
	return ""
}

func (x *LicenseUser) GetUser() *ObjectId {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LicenseUser) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *LicenseUser) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type Permission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // [required] e.g.: 'read', 'playback_record_file', ...
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`   // [optional] e.g.: 'Select Any'
	Usage string `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"` // [optional] e.g.: 'Grants permission to select any objects'
}

func (x *Permission) Reset() {
	*x = Permission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authN_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_authN_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_authN_proto_rawDescGZIP(), []int{4}
}

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

// https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
type Userinfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dc                int64          `protobuf:"varint,2,opt,name=dc,proto3" json:"dc,omitempty"`                          // current domain component id
	Domain            string         `protobuf:"bytes,3,opt,name=domain,json=realm,proto3" json:"domain,omitempty"`        // session domain.name
	UserId            int64          `protobuf:"varint,4,opt,name=user_id,json=sub,proto3" json:"user_id,omitempty"`       // current user.id
	Name              string         `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`                       // current user.id
	Username          string         `protobuf:"bytes,6,opt,name=username,json=nickname,proto3" json:"username,omitempty"` // session end-user login
	PreferredUsername string         `protobuf:"bytes,7,opt,name=preferred_username,proto3" json:"preferred_username,omitempty"`
	Extension         string         `protobuf:"bytes,8,opt,name=extension,json=phone_number,proto3" json:"extension,omitempty"`
	Scope             []*Objclass    `protobuf:"bytes,10,rep,name=scope,proto3" json:"scope,omitempty"`                           // map[class]dac
	Roles             []*ObjectId    `protobuf:"bytes,11,rep,name=roles,proto3" json:"roles,omitempty"`                           // map[role]oid
	License           []*LicenseUser `protobuf:"bytes,12,rep,name=license,proto3" json:"license,omitempty"`                       // map[key]details
	Permissions       []*Permission  `protobuf:"bytes,13,rep,name=permissions,proto3" json:"permissions,omitempty"`               //
	UpdatedAt         int64          `protobuf:"varint,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // user last updated
	ExpiresAt         int64          `protobuf:"varint,21,opt,name=expires_at,json=exp,proto3" json:"expires_at,omitempty"`       // unix
}

func (x *Userinfo) Reset() {
	*x = Userinfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authN_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Userinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userinfo) ProtoMessage() {}

func (x *Userinfo) ProtoReflect() protoreflect.Message {
	mi := &file_authN_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userinfo.ProtoReflect.Descriptor instead.
func (*Userinfo) Descriptor() ([]byte, []int) {
	return file_authN_proto_rawDescGZIP(), []int{5}
}

func (x *Userinfo) GetDc() int64 {
	if x != nil {
		return x.Dc
	}
	return 0
}

func (x *Userinfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Userinfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Userinfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Userinfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Userinfo) GetPreferredUsername() string {
	if x != nil {
		return x.PreferredUsername
	}
	return ""
}

func (x *Userinfo) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *Userinfo) GetScope() []*Objclass {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Userinfo) GetRoles() []*ObjectId {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Userinfo) GetLicense() []*LicenseUser {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *Userinfo) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Userinfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Userinfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_authN_proto protoreflect.FileDescriptor

var file_authN_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x4e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61,
	0x70, 0x69, 0x22, 0x34, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x98, 0x01, 0x0a, 0x08, 0x4f, 0x62, 0x6a,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x62, 0x61, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x61,
	0x62, 0x61, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x62, 0x61, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x6f, 0x62, 0x61, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x62, 0x61, 0x63, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x72, 0x62, 0x61, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x2e, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x0b, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x72, 0x6f, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x22, 0x46, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa9,
	0x03, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x64,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x64, 0x63, 0x12, 0x15, 0x0a, 0x06, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x61,
	0x6c, 0x6d, 0x12, 0x14, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x75, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x70, 0x65, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f,
	0x62, 0x6a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x23,
	0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x52, 0x05, 0x72, 0x6f,
	0x6c, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x0c,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x63, 0x65, 0x6e,
	0x73, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0d,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x14, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x17, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x32, 0x39, 0x0a, 0x04, 0x41, 0x75,
	0x74, 0x68, 0x12, 0x31, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x00, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x62, 0x69, 0x74, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authN_proto_rawDescOnce sync.Once
	file_authN_proto_rawDescData = file_authN_proto_rawDesc
)

func file_authN_proto_rawDescGZIP() []byte {
	file_authN_proto_rawDescOnce.Do(func() {
		file_authN_proto_rawDescData = protoimpl.X.CompressGZIP(file_authN_proto_rawDescData)
	})
	return file_authN_proto_rawDescData
}

var file_authN_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_authN_proto_goTypes = []interface{}{
	(*UserinfoRequest)(nil), // 0: api.UserinfoRequest
	(*Objclass)(nil),        // 1: api.Objclass
	(*ObjectId)(nil),        // 2: api.ObjectId
	(*LicenseUser)(nil),     // 3: api.LicenseUser
	(*Permission)(nil),      // 4: api.Permission
	(*Userinfo)(nil),        // 5: api.Userinfo
}
var file_authN_proto_depIdxs = []int32{
	2, // 0: api.LicenseUser.user:type_name -> api.ObjectId
	1, // 1: api.Userinfo.scope:type_name -> api.Objclass
	2, // 2: api.Userinfo.roles:type_name -> api.ObjectId
	3, // 3: api.Userinfo.license:type_name -> api.LicenseUser
	4, // 4: api.Userinfo.permissions:type_name -> api.Permission
	0, // 5: api.Auth.UserInfo:input_type -> api.UserinfoRequest
	5, // 6: api.Auth.UserInfo:output_type -> api.Userinfo
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_authN_proto_init() }
func file_authN_proto_init() {
	if File_authN_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authN_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserinfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authN_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Objclass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authN_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authN_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LicenseUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authN_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Permission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authN_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Userinfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authN_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authN_proto_goTypes,
		DependencyIndexes: file_authN_proto_depIdxs,
		MessageInfos:      file_authN_proto_msgTypes,
	}.Build()
	File_authN_proto = out.File
	file_authN_proto_rawDesc = nil
	file_authN_proto_goTypes = nil
	file_authN_proto_depIdxs = nil
}
