// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: media.proto

package storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MediaFileService service

func NewMediaFileServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MediaFileService service

type MediaFileService interface {
	ReadMediaFileNA(ctx context.Context, in *ReadMediaFileRequest, opts ...client.CallOption) (*MediaFile, error)
}

type mediaFileService struct {
	c    client.Client
	name string
}

func NewMediaFileService(name string, c client.Client) MediaFileService {
	return &mediaFileService{
		c:    c,
		name: name,
	}
}

func (c *mediaFileService) ReadMediaFileNA(ctx context.Context, in *ReadMediaFileRequest, opts ...client.CallOption) (*MediaFile, error) {
	req := c.c.NewRequest(c.name, "MediaFileService.ReadMediaFileNA", in)
	out := new(MediaFile)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MediaFileService service

type MediaFileServiceHandler interface {
	ReadMediaFileNA(context.Context, *ReadMediaFileRequest, *MediaFile) error
}

func RegisterMediaFileServiceHandler(s server.Server, hdlr MediaFileServiceHandler, opts ...server.HandlerOption) error {
	type mediaFileService interface {
		ReadMediaFileNA(ctx context.Context, in *ReadMediaFileRequest, out *MediaFile) error
	}
	type MediaFileService struct {
		mediaFileService
	}
	h := &mediaFileServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MediaFileService{h}, opts...))
}

type mediaFileServiceHandler struct {
	MediaFileServiceHandler
}

func (h *mediaFileServiceHandler) ReadMediaFileNA(ctx context.Context, in *ReadMediaFileRequest, out *MediaFile) error {
	return h.MediaFileServiceHandler.ReadMediaFileNA(ctx, in, out)
}
