// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: chat/messages/agents.proto

package messages

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AgentChatsService service

func NewAgentChatsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "AgentChatsService.GetAgentChats",
			Path:    []string{"/agent/chats"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
	}
}

// Client API for AgentChatsService service

type AgentChatsService interface {
	GetAgentChats(ctx context.Context, in *GetAgentChatsRequest, opts ...client.CallOption) (*GetAgentChatsResponse, error)
}

type agentChatsService struct {
	c    client.Client
	name string
}

func NewAgentChatsService(name string, c client.Client) AgentChatsService {
	return &agentChatsService{
		c:    c,
		name: name,
	}
}

func (c *agentChatsService) GetAgentChats(ctx context.Context, in *GetAgentChatsRequest, opts ...client.CallOption) (*GetAgentChatsResponse, error) {
	req := c.c.NewRequest(c.name, "AgentChatsService.GetAgentChats", in)
	out := new(GetAgentChatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgentChatsService service

type AgentChatsServiceHandler interface {
	GetAgentChats(context.Context, *GetAgentChatsRequest, *GetAgentChatsResponse) error
}

func RegisterAgentChatsServiceHandler(s server.Server, hdlr AgentChatsServiceHandler, opts ...server.HandlerOption) error {
	type agentChatsService interface {
		GetAgentChats(ctx context.Context, in *GetAgentChatsRequest, out *GetAgentChatsResponse) error
	}
	type AgentChatsService struct {
		agentChatsService
	}
	h := &agentChatsServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "AgentChatsService.GetAgentChats",
		Path:    []string{"/agent/chats"},
		Method:  []string{"GET"},
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&AgentChatsService{h}, opts...))
}

type agentChatsServiceHandler struct {
	AgentChatsServiceHandler
}

func (h *agentChatsServiceHandler) GetAgentChats(ctx context.Context, in *GetAgentChatsRequest, out *GetAgentChatsResponse) error {
	return h.AgentChatsServiceHandler.GetAgentChats(ctx, in, out)
}
