// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: chat/messages/agents.proto

package messages

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AgentChatService service

func NewAgentChatServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "AgentChatService.GetAgentChats",
			Path:    []string{"/agent/chats"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		{
			Name:    "AgentChatService.GetAgentChatsCounter",
			Path:    []string{"/agent/chats/counter"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		{
			Name:    "AgentChatService.MarkChatProcessed",
			Path:    []string{"/agent/chats/{chat_id}"},
			Method:  []string{"PATCH"},
			Handler: "rpc",
		},
	}
}

// Client API for AgentChatService service

type AgentChatService interface {
	GetAgentChats(ctx context.Context, in *GetAgentChatsRequest, opts ...client.CallOption) (*GetAgentChatsResponse, error)
	GetAgentChatsCounter(ctx context.Context, in *GetAgentChatsCounterRequest, opts ...client.CallOption) (*GetAgentChatsCounterResponse, error)
	MarkChatProcessed(ctx context.Context, in *MarkChatProcessedRequest, opts ...client.CallOption) (*MarkChatProcessedResponse, error)
}

type agentChatService struct {
	c    client.Client
	name string
}

func NewAgentChatService(name string, c client.Client) AgentChatService {
	return &agentChatService{
		c:    c,
		name: name,
	}
}

func (c *agentChatService) GetAgentChats(ctx context.Context, in *GetAgentChatsRequest, opts ...client.CallOption) (*GetAgentChatsResponse, error) {
	req := c.c.NewRequest(c.name, "AgentChatService.GetAgentChats", in)
	out := new(GetAgentChatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentChatService) GetAgentChatsCounter(ctx context.Context, in *GetAgentChatsCounterRequest, opts ...client.CallOption) (*GetAgentChatsCounterResponse, error) {
	req := c.c.NewRequest(c.name, "AgentChatService.GetAgentChatsCounter", in)
	out := new(GetAgentChatsCounterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentChatService) MarkChatProcessed(ctx context.Context, in *MarkChatProcessedRequest, opts ...client.CallOption) (*MarkChatProcessedResponse, error) {
	req := c.c.NewRequest(c.name, "AgentChatService.MarkChatProcessed", in)
	out := new(MarkChatProcessedResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgentChatService service

type AgentChatServiceHandler interface {
	GetAgentChats(context.Context, *GetAgentChatsRequest, *GetAgentChatsResponse) error
	GetAgentChatsCounter(context.Context, *GetAgentChatsCounterRequest, *GetAgentChatsCounterResponse) error
	MarkChatProcessed(context.Context, *MarkChatProcessedRequest, *MarkChatProcessedResponse) error
}

func RegisterAgentChatServiceHandler(s server.Server, hdlr AgentChatServiceHandler, opts ...server.HandlerOption) error {
	type agentChatService interface {
		GetAgentChats(ctx context.Context, in *GetAgentChatsRequest, out *GetAgentChatsResponse) error
		GetAgentChatsCounter(ctx context.Context, in *GetAgentChatsCounterRequest, out *GetAgentChatsCounterResponse) error
		MarkChatProcessed(ctx context.Context, in *MarkChatProcessedRequest, out *MarkChatProcessedResponse) error
	}
	type AgentChatService struct {
		agentChatService
	}
	h := &agentChatServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "AgentChatService.GetAgentChats",
		Path:    []string{"/agent/chats"},
		Method:  []string{"GET"},
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "AgentChatService.GetAgentChatsCounter",
		Path:    []string{"/agent/chats/counter"},
		Method:  []string{"GET"},
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "AgentChatService.MarkChatProcessed",
		Path:    []string{"/agent/chats/{chat_id}"},
		Method:  []string{"PATCH"},
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&AgentChatService{h}, opts...))
}

type agentChatServiceHandler struct {
	AgentChatServiceHandler
}

func (h *agentChatServiceHandler) GetAgentChats(ctx context.Context, in *GetAgentChatsRequest, out *GetAgentChatsResponse) error {
	return h.AgentChatServiceHandler.GetAgentChats(ctx, in, out)
}

func (h *agentChatServiceHandler) GetAgentChatsCounter(ctx context.Context, in *GetAgentChatsCounterRequest, out *GetAgentChatsCounterResponse) error {
	return h.AgentChatServiceHandler.GetAgentChatsCounter(ctx, in, out)
}

func (h *agentChatServiceHandler) MarkChatProcessed(ctx context.Context, in *MarkChatProcessedRequest, out *MarkChatProcessedResponse) error {
	return h.AgentChatServiceHandler.MarkChatProcessed(ctx, in, out)
}
