// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: portal_messages.proto

package portal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	messages "github.com/webitel/chat_manager/api/proto/chat/messages"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ChatMessages service

func NewChatMessagesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ChatMessages service

type ChatMessagesService interface {
	// Broadcast message `from` given bot profile to `peer` recipient(s)
	BroadcastMessage(ctx context.Context, in *messages.BroadcastMessageRequest, opts ...client.CallOption) (*messages.BroadcastMessageResponse, error)
}

type chatMessagesService struct {
	c    client.Client
	name string
}

func NewChatMessagesService(name string, c client.Client) ChatMessagesService {
	return &chatMessagesService{
		c:    c,
		name: name,
	}
}

func (c *chatMessagesService) BroadcastMessage(ctx context.Context, in *messages.BroadcastMessageRequest, opts ...client.CallOption) (*messages.BroadcastMessageResponse, error) {
	req := c.c.NewRequest(c.name, "ChatMessages.BroadcastMessage", in)
	out := new(messages.BroadcastMessageResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ChatMessages service

type ChatMessagesHandler interface {
	// Broadcast message `from` given bot profile to `peer` recipient(s)
	BroadcastMessage(context.Context, *messages.BroadcastMessageRequest, *messages.BroadcastMessageResponse) error
}

func RegisterChatMessagesHandler(s server.Server, hdlr ChatMessagesHandler, opts ...server.HandlerOption) error {
	type chatMessages interface {
		BroadcastMessage(ctx context.Context, in *messages.BroadcastMessageRequest, out *messages.BroadcastMessageResponse) error
	}
	type ChatMessages struct {
		chatMessages
	}
	h := &chatMessagesHandler{hdlr}
	return s.Handle(s.NewHandler(&ChatMessages{h}, opts...))
}

type chatMessagesHandler struct {
	ChatMessagesHandler
}

func (h *chatMessagesHandler) BroadcastMessage(ctx context.Context, in *messages.BroadcastMessageRequest, out *messages.BroadcastMessageResponse) error {
	return h.ChatMessagesHandler.BroadcastMessage(ctx, in, out)
}
