name: PR (webitel-messages)
run-name: "webitel-messages@pr${{ github.event.pull_request.number }}#${{ github.run_number }} - ${{ github.event.pull_request.title }}"

on:
  pull_request:

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/golang-prepare.yml@v1.0.5
    with:
      development-branch: ${{ github.event.repository.default_branch }}
      triggered-branch: ${{ github.event.pull_request.base.ref }}

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/golang-checks.yml@v1.0.5
    permissions:
      contents: read
      actions: read
      security-events: write

  compile:
    name: Build
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/golang-build.yml@v1.0.5
    with:
      binary-name: messages
      ldflags: >
        -s -w
        -X github.com/webitel/chat_manager/cmd.GitTag=${{ github.ref_name }}
        -X github.com/webitel/chat_manager/cmd.GitCommit=${{ github.sha }}
        -X github.com/webitel/chat_manager/cmd.BuildDate=${{ github.event.head_commit.timestamp }}
        

      version: ${{ needs.prepare.outputs.version }}
      version-build: ${{ github.run_number }}
      prerelease: dev~pr${{ github.event.pull_request.number }}
      package-name: ${{ vars.SERVICE_NAME }}
      package-description: ${{ github.event.repository.description }}
      package-contents: |
        src=scripts/systemd/messages-bot.service dst=/etc/systemd/system/webitel-messages-bot.service type=config
        src=scripts/systemd/messages-srv.service dst=/etc/systemd/system/webitel-messages-srv.service type=config
        src=bot/telegram/gotd/public/ dst=/var/lib/webitel/public-html
        

      scripts: |
        
