name: Workflow (webitel-messages)
run-name: "webitel-messages@${{ github.ref_name }}#${{ github.run_number }} - ${{ github.event.head_commit.message }}"

on:
  push:
    branches: [ main, "v[0-9]+.[0-9]+" ]

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/golang-prepare.yml@v1.0.5
    with:
      development-branch: ${{ github.event.repository.default_branch }}
      triggered-branch: ${{ github.ref_name }}

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/golang-checks.yml@v1.0.5
    permissions:
      contents: read
      actions: read
      security-events: write

  compile:
    name: Build
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/golang-build.yml@v1.0.5
    with:
      binary-name: messages
      ldflags: >
        -s -w
        -X github.com/webitel/chat_manager/cmd.GitTag=${{ github.ref_name }}
        -X github.com/webitel/chat_manager/cmd.GitCommit=${{ github.sha }}
        -X github.com/webitel/chat_manager/cmd.BuildDate=${{ github.event.head_commit.timestamp }}
        

      version: ${{ needs.prepare.outputs.version }}
      version-build: ${{ github.run_number }}
      prerelease: ${{ github.event.repository.default_branch == github.ref_name && 'dev' || '' }}
      package-name: webitel-messages
      package-description: ${{ github.event.repository.description }}
      package-contents: |
        src=scripts/systemd/messages-bot.service dst=/etc/systemd/system/webitel-messages-bot.service type=config
        src=scripts/systemd/messages-srv.service dst=/etc/systemd/system/webitel-messages-srv.service type=config
        src=bot/telegram/gotd/public/ dst=/var/lib/webitel/public-html
        

      package-depends: 
      scripts: |
        

  deploy:
    name: Deploy
    needs: [ prepare, compile ]
    uses: webitel/reusable-workflows/.github/workflows/_deploy.yml@v1.0.5
    permissions: { contents: write }
    secrets: inherit
    with:
      tag: ${{ github.event.repository.default_branch != github.ref_name && format('{0}-{1}', needs.prepare.outputs.version, github.run_number) || '' }}
      tag-target-commitish: ${{ github.sha }}
      repository-environment: ${{ github.event.repository.default_branch == github.ref_name && 'acceptance' || format('{0}-releases', needs.prepare.outputs.version) }}
      deb-package-pattern: "webitel-messages*.deb"
      deb-component: ${{ github.event.repository.default_branch == github.ref_name && 'dev' || format('{0}-releases', needs.prepare.outputs.version) }}
      deb-codename: ${{ vars.DEB_CODENAME }}
      deb-aws-bucket-name: ${{ vars.DEB_AWS_BUCKET_NAME }}
      deb-aws-bucket-region: ${{ vars.DEB_AWS_DEFAULT_REGION }}
